//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace CommonWeal.NGOWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public UserLogin()
        {
            this.RegisteredUsers = new HashSet<RegisteredUser>();
            this.NGOUsers = new HashSet<NGOUser>();
        }
       
  
        public int LoginID { get; set; }
        [Required (ErrorMessage="This field is required")]
        public string LoginPassword { get; set; }
        public Nullable<int> LoginUserType { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail")]
        public string LoginEmailID { get; set; }
        public bool IsActive { get; set; }
        public bool IsBlock { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<RegisteredUser> RegisteredUsers { get; set; }
        public virtual RoleType RoleType { get; set; }
        public virtual ICollection<NGOUser> NGOUsers { get; set; }
    }
}
