//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOUserPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryMaster
    {
        public CountryMaster()
        {
            this.StateMaster = new HashSet<StateMaster>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string CountryCode { get; set; }
    
        public virtual ICollection<StateMaster> StateMaster { get; set; }
    }
}
