//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOUserPage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class commonwealdbEntities : DbContext
    {
        public commonwealdbEntities()
            : base("name=commonwealdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CityMaster> CityMaster { get; set; }
        public DbSet<CountryMaster> CountryMaster { get; set; }
        public DbSet<operationalArea> operationalArea { get; set; }
        public DbSet<StateMaster> StateMaster { get; set; }
        public DbSet<tbl_comment> tbl_comment { get; set; }
        public DbSet<tbl_commentlike> tbl_commentlike { get; set; }
        public DbSet<tbl_login> tbl_login { get; set; }
        public DbSet<tbl_ngo> tbl_ngo { get; set; }
        public DbSet<tbl_post> tbl_post { get; set; }
        public DbSet<tbl_postlike> tbl_postlike { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<AreaOfInterest> AreaOfInterest { get; set; }
    }
}
