//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOUserPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_post
    {
        public tbl_post()
        {
            this.tbl_comment = new HashSet<tbl_comment>();
            this.tbl_postlike = new HashSet<tbl_postlike>();
        }
    
        public long post_id { get; set; }
        public long login_id { get; set; }
        public System.DateTime post_datetime { get; set; }
        public string post_type { get; set; }
        public string post_conent { get; set; }
        public string post_url { get; set; }
        public Nullable<long> post_likeCount { get; set; }
        public Nullable<int> post_commentCount { get; set; }
    
        public virtual ICollection<tbl_comment> tbl_comment { get; set; }
        public virtual tbl_login tbl_login { get; set; }
        public virtual ICollection<tbl_postlike> tbl_postlike { get; set; }
    }
}
