//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOUserPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comment
    {
        public tbl_comment()
        {
            this.tbl_commentlike = new HashSet<tbl_commentlike>();
        }
    
        public long comment_id { get; set; }
        public long post_id { get; set; }
        public string comment_text { get; set; }
        public System.DateTime comment_datetime { get; set; }
        public Nullable<int> comment_likecount { get; set; }
        public Nullable<bool> comment_isReply { get; set; }
        public long login_id { get; set; }
    
        public virtual ICollection<tbl_commentlike> tbl_commentlike { get; set; }
        public virtual tbl_login tbl_login { get; set; }
        public virtual tbl_post tbl_post { get; set; }
    }
}
