//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOUserPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public long user_id { get; set; }
        public string login_Email { get; set; }
        public string login_password { get; set; }
        public string login_userName { get; set; }
        public string login_userType { get; set; }
        public string Login_mobileNumber { get; set; }
        public long login_id { get; set; }
    
        public virtual tbl_login tbl_login { get; set; }
    }
}
