//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOUserPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_commentlike
    {
        public long commentlike_id { get; set; }
        public long comment_id { get; set; }
        public long login_id { get; set; }
        public Nullable<System.DateTime> commentlike_datetime { get; set; }
    
        public virtual tbl_comment tbl_comment { get; set; }
        public virtual tbl_login tbl_login { get; set; }
    }
}
