//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOUserPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_postlike
    {
        public long postlike_id { get; set; }
        public long login_id { get; set; }
        public long post_id { get; set; }
        public Nullable<System.DateTime> like_datetime { get; set; }
    
        public virtual tbl_login tbl_login { get; set; }
        public virtual tbl_post tbl_post { get; set; }
    }
}
