//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace NGOUserPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ngo
    {
        public long ngo_UserId { get; set; }
        public string ngo_UniqueuId { get; set; }
        public Nullable<long> ngo_Telephone { get; set; }
        public string ngo_City { get; set; }
        public string ngo_State { get; set; }
        public string ngo_Address { get; set; }
        public string ngo_ChairmanPersonName { get; set; }
        public string ngo_PhotoId { get; set; }
        public string ngo_ParentOrganisation { get; set; }
        public string ngo_RegisteredWith { get; set; }
        public string ngo_RegistrationNumber { get; set; }
        public string ngo_CityOfRegistration { get; set; }

        //[DataType(DataType.Date)]
        //public Nullable<System.DateTime> ngo_DateOfRegistration { get; set; }
       
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public DateTime ngo_DateOfRegistration { get; set; }



        public string ngo_CopyOfRegistration { get; set; }
        public string ngo_Type { get; set; }
        public string ngo_fcraNumber { get; set; }
        public string ngo_AreaOfIntrest { get; set; }
        public string ngo_OperationalAera { get; set; }
        public string ngo_WebsiteUrl { get; set; }
        public string ngo_Email { get; set; }
        [DataType(DataType.Password)]
        public string ngo_password { get; set; }
        public string ngo_userName { get; set; }
        public string ngo_mobileNumber { get; set; }
        public Nullable<long> login_id { get; set; }

    }
}
