CREATE TABLE [dbo].[NGOUser] (
    [NGOUserId]          INT           IDENTITY (1, 1) NOT NULL,
    [UniqueuId]          VARCHAR (50)  NULL,
    [NGOName]            VARCHAR (50)  NULL,
    [NGOEmailID]         VARCHAR (100) NULL,
    [NGOPassword]        VARCHAR (100) NULL,
    [LoginID]            INT           NULL,
    [NGOKey]             VARCHAR (100) NULL,
    [NGOProfilePic]      VARCHAR (100) NULL,
    [Telephone]          VARCHAR (50)  NULL,
    [Mobile]             VARCHAR (50)  NULL,
    [city]               INT           NULL,
    [State]              INT           NULL,
    [LoginUserType]      INT           NULL,
    [NGOAddress]         VARCHAR (100) NULL,
    [ChairmanName]       VARCHAR (50)  NULL,
    [ChairmanID]         VARCHAR (MAX) NULL,
    [ParentOrganisation] VARCHAR (50)  NULL,
    [RegisteredWith]     VARCHAR (50)  NULL,
    [RegistrationNumber] VARCHAR (50)  NULL,
    [RegistrationProof]  VARCHAR (MAX) NULL,
    [CityOfRegistration] VARCHAR (50)  NULL,
    [DateOfRegistration] DATE          NULL,
    [FCRANumber]         VARCHAR (50)  NULL,
    [AreaOfIntrest]      VARCHAR (500) NULL,
    [OperationalArea]    VARCHAR (50)  NULL,
    [WebsiteUrl]         VARCHAR (500) NULL,
    [IsActive]           BIT           CONSTRAINT [DF_NGOUser_IsActive] DEFAULT ((0)) NULL,
    [IsBlock]            BIT           CONSTRAINT [DF_NGOUser_IsBlock] DEFAULT ((0)) NULL,
    [CreatedOn]          DATETIME      NULL,
    [ModifiedOn]         DATETIME      NULL,
    [CreatedBy]          VARCHAR (100) NULL,
    [IsWarn]             BIT           NULL,
    [AboutUs]            VARCHAR (MAX) NULL,
    [IsDecline]          BIT           CONSTRAINT [DF_NGOUser_IsDecline] DEFAULT ((0)) NULL,
    [PostCount]          INT           NULL,
    [country]            INT           NULL,
    CONSTRAINT [PK_NGOUser] PRIMARY KEY CLUSTERED ([NGOUserId] ASC),
    CONSTRAINT [FK_NGOUser_UserLogin] FOREIGN KEY ([LoginID]) REFERENCES [dbo].[User] ([LoginID])
);

