//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonWeal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int ChatID { get; set; }
        public int LoginID { get; set; }
        public string Message { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
