//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonWeal.Data
{
    using System;
    
    public partial class usp_GetNGORequest_Result1
    {
        public string NGOName { get; set; }
        public string NGOEmailID { get; set; }
        public string WebsiteUrl { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
