//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonWeal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationRequest
    {
        public DonationRequest()
        {
            this.DonationDetails = new HashSet<DonationDetail>();
        }
    
        public int RequestID { get; set; }
        public string ImgeUrl { get; set; }
        public string Description { get; set; }
        public int RequestNGOId { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> ItemCost { get; set; }
    
        public virtual ICollection<DonationDetail> DonationDetails { get; set; }
        public virtual DonationRequest DonationRequest1 { get; set; }
        public virtual DonationRequest DonationRequest2 { get; set; }
    }
}
