//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonWeal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationDetail
    {
        public DonationDetail()
        {
            this.DonarDetails = new HashSet<DonarDetail>();
        }
    
        public int ItemID { get; set; }
        public int RequestID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public Nullable<int> DonatedCount { get; set; }
        public Nullable<int> ItemRequire { get; set; }
        public Nullable<int> DonatedCost { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> UnitPrice { get; set; }
    
        public virtual ICollection<DonarDetail> DonarDetails { get; set; }
        public virtual DonationRequest DonationRequest { get; set; }
    }
}
