//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonWeal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonarDetail
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> DonarLoginID { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> Donatecount { get; set; }
    
        public virtual DonationDetail DonationDetail { get; set; }
    }
}
