//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonWeal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingArea
    {
        public int WorkingAreaID { get; set; }
        public int LoginID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    }
}
