//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authority_Link
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> L1ID { get; set; }
        public Nullable<int> L2ID { get; set; }
        public Nullable<int> L3ID { get; set; }
    }
}
