//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Details
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Vertical { get; set; }
        public string Location { get; set; }
        public string Gender { get; set; }
        public string DOJ { get; set; }
        public string L1 { get; set; }
        public string L1Email { get; set; }
        public string L2 { get; set; }
        public string L2Email { get; set; }
        public string L3 { get; set; }
        public string L3Email { get; set; }
    }
}
