//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Designation { get; set; }
        public int Department { get; set; }
        public int Vertical { get; set; }
        public string Loction { get; set; }
        public bool Gender { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Email { get; set; }
        public int EmployeeID { get; set; }
    }
}
