//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36365
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonWeal.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonWeal.Data.ModelMessages", typeof(ModelMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password does not match.
        /// </summary>
        internal static string Generic_ConfirmPassword {
            get {
                return ResourceManager.GetString("Generic_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid email.
        /// </summary>
        internal static string Generic_Email {
            get {
                return ResourceManager.GetString("Generic_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 10 digit numbers only.
        /// </summary>
        internal static string Generic_MobileNumberLength {
            get {
                return ResourceManager.GetString("Generic_MobileNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter alphabets only.
        /// </summary>
        internal static string Generic_OnlyAlphabets {
            get {
                return ResourceManager.GetString("Generic_OnlyAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid numbers only.
        /// </summary>
        internal static string Generic_OnlyNumbers {
            get {
                return ResourceManager.GetString("Generic_OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Length should be minimum 8 characters with uppercase lowercase and special character.
        /// </summary>
        internal static string Generic_passwordStrength {
            get {
                return ResourceManager.GetString("Generic_passwordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is mandatory..
        /// </summary>
        internal static string Generic_Required {
            get {
                return ResourceManager.GetString("Generic_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered value exceeds the required length.
        /// </summary>
        internal static string Generic_StringLength {
            get {
                return ResourceManager.GetString("Generic_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exist.
        /// </summary>
        internal static string Generic_UniqueEmail {
            get {
                return ResourceManager.GetString("Generic_UniqueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid URL.
        /// </summary>
        internal static string Generic_URL {
            get {
                return ResourceManager.GetString("Generic_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid URL.
        /// </summary>
        internal static string NGO_ValidURL {
            get {
                return ResourceManager.GetString("NGO_ValidURL", resourceCulture);
            }
        }
    }
}
